version: '3.8'

services:
  nav2-multirobots:
    build: .
    image: ros2-nav2-multirobots:latest
    container_name: cerise-nav2
    privileged: true
    network_mode: host
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - TURTLEBOT3_MODEL=waffle
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./src:/workspace/src:rw
      - ./install:/workspace/install:rw
    command: >
      bash -c "ros2 launch cerise_4robots cerise_2robots.py"
